### ISSUE TITLE
Nested Boards is broken in the latest TP3 version

### ISSUE THREAD

**Issue by designermonkey** [TargetProcess/TP3MashupLibrary#187]
I had a custom version that worked one day, and then it was broken the next. I reverted back to the version listed in the TP Mashups library, and this is also broken.

When loading the nested board, the same board that is currently displayed is displayed in the iframe.

I've tried to figure this out, but as I don't know how the API works other than making slight alterations to this mashup, I have no idea how to fix it.

**Comment by roadhump** [comment]
Fixed https://github.com/TargetProcess/TP3MashupLibrary/pull/188

**Comment by designermonkey** [comment]
Oh awesome, thank you!

**Comment by designermonkey** [comment]
This is broken again:

```
Filter is incorrect
Key TupleExpression was not found in map
```

**Comment by roadhump** [comment]
should be fixed now https://github.com/TargetProcess/TP3MashupLibrary/pull/207

**Comment by designermonkey** [comment]
Certainly is, thanks very much :D
