### ISSUE TITLE
Support for multiple processes

### ISSUE THREAD

**Issue by JohnCatn** [TargetProcess/TP3MashupLibrary#205]
I have two processes I'd like to utilise the mashup on, I have the following config but the constraint is not being applied to the second process.  I'm unsure if this is a supported feature.

```
tau.mashups    
    .addModule('CFConstraints.config', function() {
        return [{
            processId: 2,
            constraints: {
                'userstory': {
                    'entityStates': [
                        {
                            name: 'Done',
                            requiredCustomFields: ['DoneReason']
                        }
                    ]                   
                }
            }
        },{
            processId: 4,
            constraints: {
                'userstory': {
                    'entityStates': [
                        {
                            name: 'Done',
                            requiredCustomFields: ['DoneReason']
                        }
                    ]                   
                }
            }
        }];
    });
```

**Comment by pinkypeaky** [comment]
Hi John,

Two processes are supported in this mashup, and the syntax you've posted here is correct.

Please double-check whether you've properly specified process ID, entity state name and custom field name for the second process.
If this doesn't help, please feel free to contact our support at support@targetprocess.com

Best wishes,
Julia.

**Comment by pinkypeaky** [comment]
John, please also make sure you refresh the page after you apply any changes to mashup configuration.

**Comment by JohnCatn** [comment]
Thanks both, I retired it this morning and it's working.  Must have just been a cache/refresh issue.
