### ISSUE TITLE
Entity Templates duplicates content

### ISSUE THREAD

**Issue by philhaz** [TargetProcess/TP3MashupLibrary#264]
We are using an on demand instance, and as of a recent update have started to see our entity templates being duplicated (shown twice) on all new entities. Currently we use it for bugs and releases, and it is affecting both.

Our current version is 3.9.0.27200. We are using the standard mashup from the library with no modifications.

**Comment by pinkypeaky** [comment]
Hi, this usually can happen when you have two version of the mashup install on the same time. Could you please check if that's the case for you?
If that doesn't help please send us details to support@targetprocess.com

Best wishes,
Julia.

**Comment by philhaz** [comment]
Hi Julia - this seems to have now resolved itself. Thanks for your help!
