### ISSUE TITLE
Sources of index.js

### ISSUE THREAD

**Issue by yesman85** [TargetProcess/TP3MashupLibrary#316]
I'm trying to roll my own version of the custom tab mashup but I don't want to use the predefined mashup so I'm trying reverse engineer this file: https://github.com/TargetProcess/TP3MashupLibrary/blob/master/Embedded%20Pages/index.js

Is there a source code for this file somewhere, it's rather complicated with just the minified version.

**Comment by pinkypeaky** [comment]
You can find the source code at https://github.com/TargetProcess/EmbeddedPages

**Comment by yesman85** [comment]
Thanks!
