### ISSUE TITLE
Dark theme broken with latest update.

### ISSUE THREAD

**Issue by wacannon** [TargetProcess/TP3MashupLibrary#344]
[Dark Theme.txt](https://github.com/TargetProcess/TP3MashupLibrary/files/2900670/Dark.Theme.txt)
The attached file includes the fix and also adds a cookie to remember your theme setting on page refresh.

**Comment by tsarevichdm** [comment]
@wacannon Thank you for contribution! Quite a lot of clients use Dark Theme and fix is very appreciated.

Could you make a pull request from these changes? That allows us to review and accept this via usual github contribution process. If that's not possible, we'll create pull request for you, but it may be a bit harder for you to contribute.

**Comment by wacannon** [comment]
Sorry I would have done that instead but didn't know how the forking process worked.  I submitted a pull request instead.
