### ISSUE TITLE
404 in Repository Details

### ISSUE THREAD

**Issue by ayurmedia** [TargetProcess/TP3MashupLibrary#353]
Main Description in the "Code" Tab on Github. Seems to be Meta-Information and not part of the readme.md.

<img width="782" alt="Screen Shot 2019-06-01 at 11 18 25" src="https://user-images.githubusercontent.com/1746990/58746487-07da0900-845f-11e9-8c4e-a0c9120957dc.png">

The Link should be 
https://dev.targetprocess.com/docs/mashups-overview
or
https://github.com/TargetProcess/User-Contributed-Mashups

The current one shows 404:
https://dev.targetprocess.com/mashups/index

<img width="1029" alt="Screen Shot 2019-06-01 at 11 14 31" src="https://user-images.githubusercontent.com/1746990/58746446-9437fc00-845e-11e9-8cd9-0ea637f6c268.png">

**Comment by pinkypeaky** [comment]
Thank you for reporting the issue! Fixed.
