### ISSUE TITLE
Mashup Description does not show up (Colorful)

### ISSUE THREAD

**Issue by ayurmedia** [TargetProcess/TP3MashupLibrary#367]
https://github.com/TargetProcess/TP3MashupLibrary/tree/master/Colorful

In the Mashup-Library the detail description is not showing the contents of the Readme.md from GitHub. 

**Mashup Teaser**
![Screen Shot 2019-06-25 at 19 56 06](https://user-images.githubusercontent.com/1746990/60121438-57bc9f00-9783-11e9-8b8b-510a133c4ca4.png)

**Mashup Detail Description**
![Screen Shot 2019-06-25 at 19 54 01](https://user-images.githubusercontent.com/1746990/60121392-38be0d00-9783-11e9-8bfa-172f71da3eac.png)

**Comment by tsarevichdm** [comment]
![image](https://user-images.githubusercontent.com/46971334/65879828-5e1d7100-e399-11e9-9718-9e9b20864c77.png)

Looks like fixed now, thanks for mentioning!
